[core]
title = "Get the Child of a Prim"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples for getting the child of a Prim."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "prim", "child", "children"]