[core]
title = "Create a Perspective Camera"

[metadata]
description = "Universal Scene Description (OpenUSD) code sample creates a perspective camera"
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "prim", "camera", "perspective"]