[core]
# The title for this code sample. Used to name the page.
title = "Select a Variant for a Variant Set"

[metadata]
#A concise description of the code sample for SEO.
description = "Universal Scene Description (OpenUSD) code sample for selecting a variant belonging to a variant set."
# Put in SEO keywords relevant to this code sample.
keywords = ["OpenUSD", "USD", "code sample", "Python", "C++", "variant set", "composition", "variant"]