[core]
# The title for this code sample. Used to name the page.
title = "Set the Value of an Attribute"

[metadata]
#A concise description of the code sample for SEO.
description = "Universal Scene Description (OpenUSD) code sample for setting the value of an Attribute."
# Put in SEO keywords relevant to this code sample.
keywords = ["OpenUSD", "USD", "code sample", "snippet", "Python", "C++", "attribute", "set", "value", "ChangeProperty", "Omniverse Kit", "Kit Commands"]