[core]
title = "Get a Prim"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples for accessing or getting a Prim on the Stage."
keywords = ["OpenUSD", "USD", "Python", "code sample", "prim", "get prim", "accessing", "IsValid", "valid"]