[core]
title = "Concatenate a Prim Path"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples for concatenating prim paths."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample",  "concatenate", "prim", "path", "AppendPath"]