[core]
title = "Concatenate a Property Name with a Prim Path"

[metadata]
description = "Universal Scene Description (USD) Python code snippet for adding an Inherit composition arc to a prim."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "prim", "property", "path", "AppendProperty"]