[core]
title = "Concatenate a Property Name with a Prim Path"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples showing how to concatenate a property name with a prim path."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "prim", "property", "path", "AppendProperty"]