[core]
title = "Get the Current Stage"

[metadata]
description = "Universal Scene Description (USD) Python code snippets for getting the current Stage in Omniverse Kit and USDView."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "stage", "Omniverse Kit", "USDView", "USD View"]