[core]
title = "Get the Parent Path for a Prim Path"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples for getting the parent path from a prim path."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "prim", "path", "GetParentPath"]