[core]
title = "Get the Currently Selected Prims"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples for getting the currently selected prim(s)."
keywords = ["OpenUSD", "USD", "Python",  "code sample", "prim", "selection", "selected", "prims", "usdview"]