[core]
title = "Get the Current Selected Prims"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples for getting the current selected prim(s)."
keywords = ["OpenUSD", "USD", "Python",  "code sample", "prim", "selection", "selected", "prims"]