[core]
title = "Add a Reference"

[metadata]
description = "Universal Scene Description (USD) Python code snippets for adding a Reference to a prim."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "prim", "reference", "AddReference"]