[core]
title = "Compute the Bounding Box for a Prim"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples showing how to compute the bounding box for a prim."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "bounding box", "prim", "omni.usd", "bbox", "ComputeWorldBound", "ComputeAlignedBox"]