[core]
title = "Create or add a Reference"

[metadata]
description = "Universal Scene Description (USD) Python code snippet for creating an Xform prim and adding a Reference in Omniverse Kit in one step."
keywords = ["OpenUSD", "USD", "Python", "snippet", "code sample", "prim", "reference", "CreateReference"]