[core]
# The title for this code sample. Used to name the page.
title = "My Code Example Code Sample"

[metadata]
#A concise description of the code sample for SEO.
description = "Universal Scene Description (OpenUSD) code sample to show how to contribute."
# Put in SEO keywords relevant to this code sample.
keywords = ["OpenUSD", "USD", "code sample", "Python", "C++", "example"]