[core]
title = "Select a Prim by Prim Path"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples showing how to select a prim using its prim path."
keywords = ["OpenUSD", "USD", "Python",  "code sample", "prim", "selection", "by path", "path", "prim path"]