[core]
title = "Select a Prim by Prim Path"

[metadata]
description = "Universal Scene Description (USD) Python code sample showing how to get the reference to a prim by using its stage path."
keywords = ["OpenUSD", "USD", "Python",  "code sample", "prim", "by", "by path", "path"]